theme: jekyll-theme-minimal
title: PHY669
subtitle: Astrophysical Techniques
description: Lab submission and other miscellaneous codes for PHY669 course (Astrophysical Techniques, Spring 2025) in IISERM
